export const boardGameCategories = [
  "Eurogames: También conocidos como 'German-style games' o 'Eurogames', se enfocan en la estrategia y la gestión de recursos más que en el azar o la confrontación directa. Ejemplos incluyen Catan y Ticket to Ride.",
  "Ameritrash: Se caracterizan por una alta interacción entre jugadores, componentes temáticos y una narrativa fuerte. Ejemplos son Descent y Zombicide.",
  "Party: Diseñados para grandes grupos y para ser jugados en un ambiente relajado. Los juegos de party suelen ser simples y rápidos, como Codenames y Dixit.",
  "Filler: Juegos cortos que se juegan en 15-30 minutos y son ideales para rellenar el tiempo entre juegos más largos. Ejemplos son Love Letter y The Mind.",
  "Cooperative: Los jugadores trabajan juntos para alcanzar un objetivo común en lugar de competir entre sí. Ejemplos incluyen Pandemic y Forbidden Island.",
  "Deck-building: Los jugadores construyen y mejoran su mazo de cartas durante el juego. Ejemplos incluyen Dominion y Ascension.",
  "Legacy: Juegos que cambian de manera permanente a lo largo de varias partidas, con modificaciones en el tablero y los componentes. Ejemplos son Risk Legacy y Gloomhaven.",
  "Wargames: Simulan batallas y conflictos militares, a menudo con reglas detalladas y componentes minuciosos. Ejemplos son Twilight Struggle y Memoir '44.",
  "Abstracto: Juegos sin tema y con mecánicas centradas en la estrategia pura. Ejemplos incluyen Go y Chess.",
  "Temático: Tienen un fuerte enfoque en una temática específica, con componentes y mecánicas que reflejan ese tema. Ejemplos son Arkham Horror y Star Wars: Imperial Assault.",
  "Rol: Juegos donde los jugadores asumen roles específicos y actúan según esos roles. Ejemplos incluyen Dungeons & Dragons y Gloomhaven.",
  "Loseta: Juegos en los que los jugadores colocan losetas o piezas similares en el tablero para construir un mapa o una estructura. Ejemplos incluyen Carcassonne y Suburbia.",
  "Worker Placement: En estos juegos, los jugadores colocan 'trabajadores' en diferentes tareas para obtener recursos o avanzar en el juego. Ejemplos son Agricola y Lords of Waterdeep.",
  "Engine-Building: Juegos donde los jugadores construyen y optimizan sistemas que generan recursos o habilidades a lo largo del juego. Ejemplos incluyen Splendor y Gloomhaven.",
  "Economic: Enfocados en la gestión de recursos y el desarrollo económico, con toma de decisiones financieras y maximización de beneficios. Ejemplos incluyen Brass: Birmingham y Le Havre.",
  "Social: Juegos que se centran en la interacción social, el engaño y la persuasión. Ejemplos incluyen The Resistance y Werewolf.",
  "Área: Juegos en los que los jugadores compiten por controlar áreas del tablero o el espacio. Ejemplos son El Grande y Power Grid.",
  "Engaño: Juegos que involucran engañar a otros jugadores, ya sea mediante deducción o engaño directo. Ejemplos son Coup y Secret Hitler.",
  "Economic-simulation: Juegos que simulan y gestionan economías y recursos, con un enfoque en la toma de decisiones económicas. Ejemplos son Brass: Birmingham y Le Havre.",
  "Destreza: Juegos que requieren habilidad física o coordinación, como lanzar piezas o manipular componentes de manera precisa. Ejemplos son Jenga y Flick 'em Up.",
  "Narración: Juegos que se centran en contar una historia o desarrollar una narrativa durante el juego. Ejemplos son Tales of the Arabian Nights y Once Upon a Time.",
  "Educativo: Diseñados para enseñar o reforzar conocimientos en áreas específicas, como matemáticas, historia o habilidades lingüísticas. Ejemplos son Math Bingo y Timeline."
];
