import {
	Alignment,
	Autoformat,
	Autosave,
	BlockQuote,
	Bold,
	Essentials,
	FontColor,
	Heading,
	Highlight,
	Indent,
	IndentBlock,
	Italic,
	Link,
	Paragraph,
	SelectAll,
  List,
  ListProperties,
  MediaEmbed,
	Strikethrough,
	Table,
	TableCaption,
	TableCellProperties,
	TableColumnResize,
	TableProperties,
	TableToolbar,
	TextTransformation,
	Underline,
	Undo,
	type EditorConfig
} from 'ckeditor5';



export const toolBarConfig = {
  toolbar: {
    items: [
      'selectAll',
      '|',
      'heading',
      '|',
      'bold',
      'italic',
      'underline',
      'strikethrough',
      '|',
      'alignment',
      '|',
      'bulletedList',
			'numberedList',
      '|',
      'fontColor',
      'highlight',
      '|',
      'link',
      'mediaEmbed',
      'insertTable',
      'blockQuote',
      '|',
      'outdent',
      'indent',
      '|',
      'undo',
      'redo',
    ],
    shouldNotGroupWhenFull: true
  },
  plugins: [
    Alignment,
    Autoformat,
    Autosave,
    BlockQuote,
    Bold,
    Essentials,
    FontColor,
    Heading,
    Highlight,
    Indent,
    IndentBlock,
    Italic,
    List,
    ListProperties,
    Link,
    MediaEmbed,
    Paragraph,
    SelectAll,
    Strikethrough,
    Table,
    TableCaption,
    TableCellProperties,
    TableColumnResize,
    TableProperties,
    TableToolbar,
    TextTransformation,
    Underline,
    Undo
  ],
  placeholder: 'Type or paste your content here!',

};
